-- ============================================================
--  Oracle XE DDL — Migração de dados do SQLite
--  Projeto de Pipeline de Migração de Dados Demonstrativo
--  Script Oracle Database XE 21c (compatível 18c+)
-- ============================================================

-- ============================================================
-- LIMPEZA (executado somente se recriar do zero)
-- ============================================================
-- A ordem de DROP respeita as dependências de FK (tb filhas antes das mães)
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'ORDER_ITEMS','ORDER_PAYMENTS','ORDER_REVIEWS',
            'ORDERS','LEADS_CLOSED','LEADS_QUALIFIED',
            'CUSTOMERS','GEOLOCATION','PRODUCTS','SELLERS',
            'PRODUCT_CATEGORY_NAME_TRANSLATION'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ============================================================
-- PRODUCT_CATEGORY_NAME_TRANSLATION
-- Tabela de domínio sem dependências externas
-- ============================================================
CREATE TABLE product_category_name_translation (
    product_category_name         VARCHAR2(100)   NOT NULL,
    product_category_name_english VARCHAR2(100)   NOT NULL,
    --
    CONSTRAINT pk_pcnt PRIMARY KEY (product_category_name)
);

COMMENT ON TABLE  product_category_name_translation                        IS 'De-para de nomes de categoria PT→EN';
COMMENT ON COLUMN product_category_name_translation.product_category_name  IS 'Nome original em português';
COMMENT ON COLUMN product_category_name_translation.product_category_name_english IS 'Tradução para inglês';


-- ============================================================
-- PRODUCTS
-- Depende de: product_category_name_translation
-- ============================================================
CREATE TABLE products (
    product_id                  VARCHAR2(50)    NOT NULL,
    product_category_name       VARCHAR2(100),          -- nullable: produtos sem categoria
    product_name_lenght         NUMBER(6,0),            -- comprimento do nome (caracteres)
    product_description_lenght  NUMBER(8,0),            -- comprimento da descrição
    product_photos_qty          NUMBER(3,0),
    product_weight_g            NUMBER(10,2),
    product_length_cm           NUMBER(8,2),
    product_height_cm           NUMBER(8,2),
    product_width_cm            NUMBER(8,2),
    --
    CONSTRAINT pk_products   PRIMARY KEY (product_id),
    CONSTRAINT fk_prod_categ FOREIGN KEY (product_category_name)
        REFERENCES product_category_name_translation (product_category_name)
        ON DELETE SET NULL,             -- categoria removida → produto fica sem categoria
    CONSTRAINT ck_prod_weight CHECK (product_weight_g    IS NULL OR product_weight_g    >= 0),
    CONSTRAINT ck_prod_length CHECK (product_length_cm   IS NULL OR product_length_cm   >= 0),
    CONSTRAINT ck_prod_height CHECK (product_height_cm   IS NULL OR product_height_cm   >= 0),
    CONSTRAINT ck_prod_width  CHECK (product_width_cm    IS NULL OR product_width_cm    >= 0),
    CONSTRAINT ck_prod_photos CHECK (product_photos_qty  IS NULL OR product_photos_qty  >= 0)
);

COMMENT ON TABLE  products IS 'Catálogo de produtos';


-- ============================================================
-- SELLERS
-- Tabela de domínio sem dependências externas
-- ============================================================
CREATE TABLE sellers (
    seller_id               VARCHAR2(50)    NOT NULL,
    seller_zip_code_prefix  NUMBER(5,0)     NOT NULL,
    seller_city             VARCHAR2(100),
    seller_state            CHAR(2),                    -- UF brasileira: SP, RJ …
    --
    CONSTRAINT pk_sellers    PRIMARY KEY (seller_id),
    CONSTRAINT ck_seller_zip CHECK (seller_zip_code_prefix BETWEEN 1000 AND 99999)
);

COMMENT ON TABLE  sellers IS 'Vendedores cadastrados na plataforma';


-- ============================================================
-- GEOLOCATION
-- Tabela de coordenadas por CEP sem FK externas
-- Nota: vários registros por CEP são possíveis (polígonos)
-- ============================================================
CREATE TABLE geolocation (
    geolocation_id              NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    geolocation_zip_code_prefix NUMBER(5,0)     NOT NULL,
    geolocation_lat             NUMBER(10,6)    NOT NULL,
    geolocation_lng             NUMBER(10,6)    NOT NULL,
    geolocation_city            VARCHAR2(100),
    geolocation_state           CHAR(2),
    --
    CONSTRAINT pk_geolocation PRIMARY KEY (geolocation_id),
    CONSTRAINT ck_geo_zip  CHECK (geolocation_zip_code_prefix BETWEEN 1000 AND 99999),
    CONSTRAINT ck_geo_lat  CHECK (geolocation_lat  BETWEEN -90  AND  90),
    CONSTRAINT ck_geo_lng  CHECK (geolocation_lng  BETWEEN -180 AND 180)
);

CREATE INDEX idx_geo_zip ON geolocation (geolocation_zip_code_prefix);

COMMENT ON TABLE  geolocation IS 'Coordenadas geográficas por prefixo de CEP';


-- ============================================================
-- CUSTOMERS
-- Sem FK para geolocation (CEP é chave lógica, não surrogate)
-- ============================================================
CREATE TABLE customers (
    customer_id             VARCHAR2(50)    NOT NULL,
    customer_unique_id      VARCHAR2(50)    NOT NULL,
    customer_zip_code_prefix NUMBER(5,0)   NOT NULL,
    customer_city           VARCHAR2(100),
    customer_state          CHAR(2),
    --
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT ck_cust_zip  CHECK (customer_zip_code_prefix BETWEEN 1000 AND 99999)
);

-- Índice útil para agrupar pedidos por cliente real (customer_unique_id)
CREATE INDEX idx_cust_unique ON customers (customer_unique_id);

COMMENT ON TABLE  customers IS 'Clientes; customer_unique_id identifica a pessoa física/jurídica';


-- ============================================================
-- ORDERS
-- Depende de: customers
-- ============================================================
CREATE TABLE orders (
    order_id                     VARCHAR2(50)  NOT NULL,
    customer_id                  VARCHAR2(50)  NOT NULL,
    order_status                 VARCHAR2(30)  NOT NULL,
    order_purchase_timestamp     TIMESTAMP,
    order_approved_at            TIMESTAMP,
    order_delivered_carrier_date TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    --
    CONSTRAINT pk_orders        PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_cust   FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id),
    CONSTRAINT ck_order_status  CHECK (order_status IN (
        'created','approved','invoiced','processing',
        'shipped','delivered','canceled','unavailable'
    ))
);

CREATE INDEX idx_orders_cust   ON orders (customer_id);
CREATE INDEX idx_orders_status ON orders (order_status);
CREATE INDEX idx_orders_purch  ON orders (order_purchase_timestamp);

COMMENT ON TABLE  orders IS 'Cabeçalho dos pedidos';


-- ============================================================
-- ORDER_ITEMS
-- Depende de: orders, products, sellers
-- ============================================================
CREATE TABLE order_items (
    order_id            VARCHAR2(50)    NOT NULL,
    order_item_id       NUMBER(4,0)     NOT NULL,   -- sequencial dentro do pedido (1,2,3…)
    product_id          VARCHAR2(50)    NOT NULL,
    seller_id           VARCHAR2(50)    NOT NULL,
    shipping_limit_date TIMESTAMP,
    price               NUMBER(12,2)    NOT NULL,
    freight_value       NUMBER(12,2)    NOT NULL,
    --
    CONSTRAINT pk_order_items     PRIMARY KEY (order_id, order_item_id),
    CONSTRAINT fk_oi_order        FOREIGN KEY (order_id)   REFERENCES orders   (order_id),
    CONSTRAINT fk_oi_product      FOREIGN KEY (product_id) REFERENCES products  (product_id),
    CONSTRAINT fk_oi_seller       FOREIGN KEY (seller_id)  REFERENCES sellers   (seller_id),
    CONSTRAINT ck_oi_price        CHECK (price         >= 0),
    CONSTRAINT ck_oi_freight      CHECK (freight_value >= 0),
    CONSTRAINT ck_oi_item_id      CHECK (order_item_id >= 1)
);

CREATE INDEX idx_oi_product ON order_items (product_id);
CREATE INDEX idx_oi_seller  ON order_items (seller_id);

COMMENT ON TABLE  order_items IS 'Itens de cada pedido (chave composta order_id + order_item_id)';


-- ============================================================
-- ORDER_PAYMENTS
-- Depende de: orders
-- ============================================================
CREATE TABLE order_payments (
    order_id             VARCHAR2(50)   NOT NULL,
    payment_sequential   NUMBER(3,0)    NOT NULL,   -- 1 = primeiro pagamento do pedido
    payment_type         VARCHAR2(30)   NOT NULL,
    payment_installments NUMBER(3,0)    NOT NULL,
    payment_value        NUMBER(12,2)   NOT NULL,
    --
    CONSTRAINT pk_order_payments  PRIMARY KEY (order_id, payment_sequential),
    CONSTRAINT fk_op_order        FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT ck_op_type         CHECK (payment_type IN (
        'credit_card','debit_card','boleto','voucher','not_defined'
    )),
    CONSTRAINT ck_op_installments CHECK (payment_installments >= 1),
    CONSTRAINT ck_op_value        CHECK (payment_value        >= 0),
    CONSTRAINT ck_op_seq          CHECK (payment_sequential   >= 1)
);

CREATE INDEX idx_op_order ON order_payments (order_id);

COMMENT ON TABLE  order_payments IS 'Formas de pagamento por pedido (pode haver mais de uma)';


-- ============================================================
-- ORDER_REVIEWS
-- Depende de: orders
-- ============================================================
CREATE TABLE order_reviews (
    review_id              VARCHAR2(50)  NOT NULL,
    order_id               VARCHAR2(50)  NOT NULL,
    review_score           NUMBER(1,0)   NOT NULL,
    review_comment_title   VARCHAR2(255),
    review_comment_message CLOB,                       -- mensagens podem ser longas
    review_creation_date   TIMESTAMP,
    review_answer_timestamp TIMESTAMP,
    --
    CONSTRAINT pk_order_reviews  PRIMARY KEY (review_id),
    CONSTRAINT fk_or_order       FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT ck_or_score       CHECK (review_score BETWEEN 1 AND 5),
    -- Um pedido pode ter mais de uma avaliação, mas evita duplicatas exatas:
    CONSTRAINT uq_or_order_rev   UNIQUE (order_id, review_id)
);

CREATE INDEX idx_or_order ON order_reviews (order_id);
CREATE INDEX idx_or_score ON order_reviews (review_score);

COMMENT ON TABLE  order_reviews IS 'Avaliações dos pedidos pelos clientes (nota 1-5)';


-- ============================================================
-- LEADS_QUALIFIED
-- Tabela de domínio de MQLs sem FK externas
-- ============================================================
CREATE TABLE leads_qualified (
    mql_id             VARCHAR2(50)   NOT NULL,
    first_contact_date DATE,                        -- apenas data, sem hora
    landing_page_id    VARCHAR2(100),
    origin             VARCHAR2(50),
    --
    CONSTRAINT pk_leads_qualified PRIMARY KEY (mql_id)
);

COMMENT ON TABLE  leads_qualified IS 'Marketing Qualified Leads (MQLs) captados';


-- ============================================================
-- LEADS_CLOSED
-- Depende de: leads_qualified e de sellers
-- ============================================================
CREATE TABLE leads_closed (
    mql_id                       VARCHAR2(50)   NOT NULL,
    seller_id                    VARCHAR2(50),          -- pode não ter seller ainda
    sdr_id                       VARCHAR2(50),
    sr_id                        VARCHAR2(50),
    won_date                     DATE,
    business_segment             VARCHAR2(100),
    lead_type                    VARCHAR2(50),
    lead_behaviour_profile       VARCHAR2(50),
    has_company                  NUMBER(1,0),           -- 0/1 booleano
    has_gtin                     NUMBER(1,0),           -- 0/1 booleano
    average_stock                VARCHAR2(50),          -- originalmente TEXT no SQLite
    business_type                VARCHAR2(50),
    declared_product_catalog_size NUMBER(10,2),
    declared_monthly_revenue      NUMBER(18,2),
    --
    CONSTRAINT pk_leads_closed    PRIMARY KEY (mql_id),
    CONSTRAINT fk_lc_mql          FOREIGN KEY (mql_id)    REFERENCES leads_qualified (mql_id),
    CONSTRAINT fk_lc_seller       FOREIGN KEY (seller_id) REFERENCES sellers (seller_id),
    CONSTRAINT ck_lc_has_company  CHECK (has_company IN (0,1) OR has_company IS NULL),
    CONSTRAINT ck_lc_has_gtin     CHECK (has_gtin    IN (0,1) OR has_gtin    IS NULL),
    CONSTRAINT ck_lc_revenue      CHECK (declared_monthly_revenue      IS NULL OR declared_monthly_revenue      >= 0),
    CONSTRAINT ck_lc_catalog_size CHECK (declared_product_catalog_size IS NULL OR declared_product_catalog_size >= 0)
);

CREATE INDEX idx_lc_seller ON leads_closed (seller_id);

COMMENT ON TABLE  leads_closed IS 'Leads que fecharam negócio (SQLs convertidos)';


-- ============================================================
-- FIM DO DDL
-- ============================================================
-- Resumo dos relacionamentos criados:
--
--  customers          ←── orders
--  orders             ←── order_items
--  orders             ←── order_payments
--  orders             ←── order_reviews
--  products           ←── order_items
--  sellers            ←── order_items
--  sellers            ←── leads_closed
--  leads_qualified    ←── leads_closed
--  product_category_name_translation ←── products
--
-- Tabelas sem FK de entrada (raízes do grafo):
--   customers, sellers, geolocation, product_category_name_translation, leads_qualified
-- ============================================================